name: flutter_everywhere
description: Mobile, Web, Desktop, Server, CLI
version: 1.0.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^0.7.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/google_fonts/
    - assets/fonts/google_fonts.json

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: assets/fonts/GalleryIcons.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf
